local L = AceLibrary("AceLocale-2.2"):new("PallyPower");
--local BS = AceLibrary("Babble-Spell-2.2")

PallyPower.commPrefix = "PLPWR";

PALLYPOWER_MAXCLASSES = 21;
PALLYPOWER_MAXPERCLASS = 8;
PALLYPOWER_NORMALBLESSINGDURATION = 30*60;
PALLYPOWER_GREATERBLESSINGDURATION = 30*60;
PALLYPOWER_MAXAURAS = PallyPower.IsTBC and 8 or 7;
PALLYPOWER_MAXBLESSINGS = 3;

PallyPower.CONFIG_DRAGHANDLE = L["DRAGHANDLE"];

PALLYPOWER_DEFAULT_VALUES = {
	buffscale = 0.75,
	configscale = 0.80,
	smartbuffs = true,
	smartpets = true,
	greaterbuffs = false,
	-- Legacy PallyPower reads these at profile root. Keep them here so the options work.
	classColor = true,
	nameClassColor = true,
	flashBuffAutoButtons = true,
	hideClassButtons = false,
	rfbuff = false,
	auras = false,
	extras = false,
	autobuff = {
		autokey1 = ",",
		autokey2 = "CTRL-,",
		autobutton = true,
		waitforpeople = false,
	},
	display = {
		-- buttons
		rows = 21,
		columns = 1,
		gapping = -1,
		buttonWidth = 100,
		buttonHeight = 34,
		alignClassButtons = "9",
		alignPlayerButtons = "compact-left",
		edges = true,
        frameLocked = false,
		hideDragHandle = false,
		hidePlayerButtons = false,
		hideClassButtons = true,
		classColor = true,
		nameClassColor = true,
		flashBuffAutoButtons = true,
		PlainButtons = false,
		HideKeyText = false,
		HideCount = false,
        LockBuffBars = false,
        HideCountText = false,
		HideTimerText = false,
	},
	ShowInParty = true,
	ShowWhenSingle = true,
	skin = "Smooth",
	cBuffNeedAll     = {r = 1.0, g = 0.0, b = 0.0, t = 0.5},
 	cBuffNeedSome    = {r = 1.0, g = 1.0, b = 0.5, t = 0.5},
 	cBuffNeedSpecial = {r = 0.0, g = 0.0, b = 1.0, t = 0.5},
	cBuffGood        = {r = 0.0, g = 0.7, b = 0.0, t = 0.5},
	sets = { 
		["primary"] = {
						seal = 0, 	-- wisdom
						aura = 0, 	-- unused by SunPower
						rf = false, -- RF off
						buffs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
					},
		["secondary"] = {
						seal = 0, 	-- wisdom
						aura = 0, 	-- unused by SunPower
						rf = false, -- RF off
						buffs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
					},
	},
	-- default assignments
	seal = 0,
	aura = 0,
	disabled = false,
	layout = "Layout 1",
}

PallyPower_Credits1 = "SunPower - based on PallyPower by Aznamir";
--PallyPower_Credits2 = "Version "..PallyPower_Version;

PallyPower.BuffBarTitle = "SunPower Devotions (%d)";

PallyPower.LegacyClassOrderV51 = {
    [1] = "NECROMANCER", [2] = "PYROMANCER", [3] = "CULTIST",
    [4] = "STARCALLER", [5] = "SUNCLERIC", [6] = "TINKER",
    [7] = "RUNEMASTER", [8] = "PRIMALIST", [9] = "REAPER",
    [10] = "VENOMANCER", [11] = "CHRONOMANCER", [12] = "BLOODMAGE",
    [13] = "GUARDIAN", [14] = "STORMBRINGER", [15] = "FELSWORN",
    [16] = "BARBARIAN", [17] = "WITCHDOCTOR", [18] = "WITCHHUNTER",
    [19] = "KNIGHTOFXOROTH", [20] = "TEMPLAR", [21] = "RANGER",
}

-- Visual order follows the existing class colors as a continuous gradient:
-- deep red -> red/orange -> gold/yellow -> green -> cyan/blue -> violet/magenta.
-- The same order is used by both the large assignment grid and the compact panel.
PallyPower.ClassID = {
    [1]  = "BLOODMAGE",
    [2]  = "BARBARIAN",
    [3]  = "PYROMANCER",
    [4]  = "SUNCLERIC",
    [5]  = "WITCHHUNTER",
    [6]  = "TINKER",
    [7]  = "CHRONOMANCER",
    [8]  = "TEMPLAR",
    [9]  = "RANGER",
    [10] = "VENOMANCER",
    [11] = "NECROMANCER",
    [12] = "FELSWORN",
    [13] = "PRIMALIST",
    [14] = "WITCHDOCTOR",
    [15] = "RUNEMASTER",
    [16] = "REAPER",
    [17] = "GUARDIAN",
    [18] = "STORMBRINGER",
    [19] = "STARCALLER",
    [20] = "CULTIST",
    [21] = "KNIGHTOFXOROTH",
}

PallyPower.ClassToID = {}
for classID, classToken in pairs(PallyPower.ClassID) do
    PallyPower.ClassToID[classToken] = classID
end
PallyPower.ClassToID["SUN_CLERIC"] = PallyPower.ClassToID["SUNCLERIC"]
PallyPower.ClassToID["BLOOD_MAGE"] = PallyPower.ClassToID["BLOODMAGE"]
PallyPower.ClassToID["STORM_BRINGER"] = PallyPower.ClassToID["STORMBRINGER"]
PallyPower.ClassToID["WITCH_DOCTOR"] = PallyPower.ClassToID["WITCHDOCTOR"]
PallyPower.ClassToID["WITCH_HUNTER"] = PallyPower.ClassToID["WITCHHUNTER"]
PallyPower.ClassToID["KNIGHT_OF_XOROTH"] = PallyPower.ClassToID["KNIGHTOFXOROTH"]
PallyPower.ClassToID["KNIGHTOF_XOROTH"] = PallyPower.ClassToID["KNIGHTOFXOROTH"]

local classIconByToken = {
    NECROMANCER    = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Necromancer",
    PYROMANCER     = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Pyromancer",
    CULTIST        = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Cultist",
    STARCALLER     = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Starcaller",
    SUNCLERIC      = "Interface\\AddOns\\SunPower\\Icons\\Classes\\SunCleric",
    TINKER         = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Tinker",
    RUNEMASTER     = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Runemaster",
    PRIMALIST      = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Primalist",
    REAPER         = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Reaper",
    VENOMANCER     = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Venomancer",
    CHRONOMANCER   = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Chronomancer",
    BLOODMAGE      = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Bloodmage",
    GUARDIAN       = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Guardian",
    STORMBRINGER   = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Stormbringer",
    FELSWORN       = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Felsworn",
    BARBARIAN      = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Barbarian",
    WITCHDOCTOR    = "Interface\\AddOns\\SunPower\\Icons\\Classes\\WitchDoctor",
    WITCHHUNTER    = "Interface\\AddOns\\SunPower\\Icons\\Classes\\WitchHunter",
    KNIGHTOFXOROTH = "Interface\\AddOns\\SunPower\\Icons\\Classes\\KnightOfXoroth",
    TEMPLAR        = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Templar",
    RANGER         = "Interface\\AddOns\\SunPower\\Icons\\Classes\\Ranger",
}

PallyPower.ClassIcons = {}
for classID, classToken in pairs(PallyPower.ClassID) do
    PallyPower.ClassIcons[classID] = classIconByToken[classToken]
end


-- CoA classes are not present in the stock WotLK RAID_CLASS_COLORS table.
-- These colors are used by the existing class-color options and config grid.
PallyPower.ClassColors = {
    -- Every CoA class has a deliberately unique RGB triplet. Similar families
    -- may be close (gold/yellow, cyan/blue), but never identical.
    NECROMANCER    = {r=0.43, g=0.58, b=0.38, t=0.82}, -- grave moss
    PYROMANCER     = {r=0.95, g=0.25, b=0.04, t=0.82}, -- ember orange
    CULTIST        = {r=0.57, g=0.20, b=0.76, t=0.82}, -- void violet
    STARCALLER     = {r=0.23, g=0.36, b=0.88, t=0.82}, -- astral indigo
    SUNCLERIC      = {r=1.00, g=0.55, b=0.06, t=0.82}, -- solar orange
    TINKER         = {r=0.63, g=0.42, b=0.16, t=0.82}, -- brass
    RUNEMASTER     = {r=0.12, g=0.70, b=0.88, t=0.82}, -- rune cyan
    PRIMALIST      = {r=0.18, g=0.57, b=0.42, t=0.82}, -- primal jade
    REAPER         = {r=0.08, g=0.43, b=0.57, t=0.82}, -- spectral teal
    VENOMANCER     = {r=0.46, g=0.82, b=0.06, t=0.82}, -- venom lime
    CHRONOMANCER   = {r=0.86, g=0.68, b=0.06, t=0.82}, -- time amber
    BLOODMAGE      = {r=0.68, g=0.03, b=0.16, t=0.82}, -- blood crimson
    GUARDIAN       = {r=0.31, g=0.46, b=0.60, t=0.82}, -- steel blue
    STORMBRINGER   = {r=0.05, g=0.48, b=0.96, t=0.82}, -- lightning blue
    FELSWORN       = {r=0.10, g=0.72, b=0.21, t=0.82}, -- fel green
    BARBARIAN      = {r=0.82, g=0.10, b=0.07, t=0.82}, -- war scarlet
    WITCHDOCTOR    = {r=0.02, g=0.60, b=0.53, t=0.82}, -- ritual turquoise
    WITCHHUNTER    = {r=0.77, g=0.45, b=0.08, t=0.82}, -- hunter bronze
    KNIGHTOFXOROTH = {r=0.66, g=0.08, b=0.39, t=0.82}, -- xoroth magenta
    TEMPLAR        = {r=0.96, g=0.82, b=0.22, t=0.82}, -- holy gold
    RANGER         = {r=0.35, g=0.49, b=0.10, t=0.82}, -- forest olive
}

PallyPower.DevotionNames = {
    [1] = "Devotion of Radiance",
    [2] = "Devotion of Dawn",
    [3] = "Devotion of Grace",
}

PallyPower.BlessingIcons = {
    [-1] = "",
    [1] = "Interface\\Icons\\INV_Misc_QuestionMark",
    [2] = "Interface\\Icons\\INV_Misc_QuestionMark",
    [3] = "Interface\\Icons\\INV_Misc_QuestionMark",
}
PallyPower.NormalBlessingIcons = PallyPower.BlessingIcons

PallyPower.AuraIcons = PallyPower.IsVanilla and {
	[-1] = "",
	[1] = "Interface\\Icons\\Spell_Holy_DevotionAura",
	[2] = "Interface\\Icons\\Spell_Holy_AuraOfLight",
	[3] = "Interface\\Icons\\Spell_Holy_MindSooth",
	[4] = "Interface\\Icons\\Spell_Shadow_SealOfKings",
	[5] = "Interface\\Icons\\Spell_Frost_WizardMark",
	[6] = "Interface\\Icons\\Spell_Fire_SealOfFire",
	[7] = "Interface\\Icons\\Spell_Holy_MindVision",
} or PallyPower.IsTBC and {
	[-1] = "",
	[1] = "Interface\\Icons\\Spell_Holy_DevotionAura",
	[2] = "Interface\\Icons\\Spell_Holy_AuraOfLight",
	[3] = "Interface\\Icons\\Spell_Holy_MindSooth",
	[4] = "Interface\\Icons\\Spell_Shadow_SealOfKings",
	[5] = "Interface\\Icons\\Spell_Frost_WizardMark",
	[6] = "Interface\\Icons\\Spell_Fire_SealOfFire",
	[7] = "Interface\\Icons\\Spell_Holy_MindVision",
	[8] = "Interface\\Icons\\Spell_Holy_CrusaderAura",
} or {
    [-1] = "",
	[1] = "Interface\\Icons\\Spell_Holy_DevotionAura",
	[2] = "Interface\\Icons\\Spell_Holy_AuraOfLight",
	[3] = "Interface\\Icons\\Spell_Holy_MindSooth",
	[4] = "Interface\\Icons\\Spell_Shadow_SealOfKings",
	[5] = "Interface\\Icons\\Spell_Frost_WizardMark",
	[6] = "Interface\\Icons\\Spell_Fire_SealOfFire",
	[7] = "Interface\\Icons\\Spell_Holy_CrusaderAura",
}

--
-- Need to add localizations
--
PALLYPOWER_CLEAR = L["PP_CLEAR"];
PALLYPOWER_REFRESH = L["PP_REFRESH"];
PALLYPOWER_OPTIONS = L["PP_OPTIONS"];
PALLYPOWER_AUTOASSIGN = L["AUTOASSIGN"]
PALLYPOWER_FREEASSIGN = L["FREEASSIGN"]

PALLYPOWER_ASSIGNMENTS1 = L["PP_RAS1"];
PALLYPOWER_ASSIGNMENTS2 = L["PP_RAS2"];

-- get translations directly
PallyPower.Spells = {
    [0] = "",
    [1] = "Devotion of Radiance",
    [2] = "Devotion of Dawn",
    [3] = "Devotion of Grace",
}
PallyPower.GSpells = { [0] = "", [1] = "Devotion of Radiance", [2] = "Devotion of Dawn", [3] = "Devotion of Grace" }

PallyPower.RFSpell = GetSpellInfo(25780) --BS["Righteous Fury"]

PallyPower.HLSpell = GetSpellInfo(635)

PallyPower.Skins = {
    ["None"] = "Interface\\Tooltips\\UI-Tooltip-Background",
	["Banto"] = "Interface\\AddOns\\PallyPower\\Skins\\Banto",
	["BantoBarReverse"] = "Interface\\AddOns\\PallyPower\\Skins\\BantoBarReverse",
	["Glaze"] = "Interface\\AddOns\\PallyPower\\Skins\\Glaze",
	["Gloss"] = "Interface\\AddOns\\PallyPower\\Skins\\Gloss",
	["Healbot"] = "Interface\\AddOns\\PallyPower\\Skins\\Healbot",
	["oCB"] = "Interface\\AddOns\\PallyPower\\Skins\\oCB",
	["Smooth"] = "Interface\\AddOns\\PallyPower\\Skins\\Smooth",
};

PallyPower.Edge = 'Interface\\Tooltips\\UI-Tooltip-Border'
--PallyPower.Edge = ''	

PallyPower.Seals = {
    [0] = "",
    [1] = GetSpellInfo(20164), -- seal of justice
	[2] = GetSpellInfo(20165), -- seal of light
    [3] = GetSpellInfo(20166), -- seal of wisdom
    [4] = GetSpellInfo(21084), -- seal of righteousness
    [5] = GetSpellInfo(53720), -- seal of martyr
    [6] = GetSpellInfo(31801), -- seal of vengeance
    [7] = GetSpellInfo(20375), -- seal of command
    [8] = GetSpellInfo(53736), -- seal of corruption
    [9] = GetSpellInfo(31892), -- seal of blood
    [10] = "",
};

PallyPower.Auras = PallyPower.IsVanilla and {
	[0] = "",
	[1] = GetSpellInfo(465), --BS["Devotion Aura"],
	[2] = GetSpellInfo(7294), --BS["Retribution Aura"],
	[3] = GetSpellInfo(19746), --BS["Concentration Aura"],
	[4] = GetSpellInfo(19876), --BS["Shadow Resistance Aura"],
	[5] = GetSpellInfo(19888), --BS["Frost Resistance Aura"],
	[6] = GetSpellInfo(19891), --BS["Fire Resistance Aura"],
	[7] = GetSpellInfo(20218), --BS["Sanctity Aura"],
} or PallyPower.IsTBC and {
	[0] = "",
	[1] = GetSpellInfo(465), --BS["Devotion Aura"],
	[2] = GetSpellInfo(7294), --BS["Retribution Aura"],
	[3] = GetSpellInfo(19746), --BS["Concentration Aura"],
	[4] = GetSpellInfo(19876), --BS["Shadow Resistance Aura"],
	[5] = GetSpellInfo(19888), --BS["Frost Resistance Aura"],
	[6] = GetSpellInfo(19891), --BS["Fire Resistance Aura"],
	[7] = GetSpellInfo(20218), --BS["Sanctity Aura"],
	[8] = GetSpellInfo(32223), --BS["Crusader Aura"],
} or {
	[0] = "",
	[1] = GetSpellInfo(465), --BS["Devotion Aura"],
	[2] = GetSpellInfo(7294), --BS["Retribution Aura"],
	[3] = GetSpellInfo(19746), --BS["Concentration Aura"],
	[4] = GetSpellInfo(19876), --BS["Shadow Resistance Aura"],
	[5] = GetSpellInfo(19888), --BS["Frost Resistance Aura"],
	[6] = GetSpellInfo(19891), --BS["Fire Resistance Aura"],
	[7] = GetSpellInfo(32223), --BS["Crusader Aura"],
}
-- Buff templates
PallyPower.Templates = PallyPower.IsVanilla and {
	[1] = {
		[1]=  {4},
		[2]=  {4},
		[3]=  {3, 1},
		[4]=  {3, 1},
		[5]=  {3, 2},
		[6]=  {4},
		[7]=  {4},
		[8]=  {4},
		[9]= {3, 2},
	},
	[2] = {
		[1]=  {4, 3, 2},
		[2]=  {4, 3, 2},
		[3]=  {1, 3, 4},
		[4]=  {1, 3, 4},
		[5]=  {1, 3, 2},
		[6]=  {4, 3, 2},
		[7]=  {4, 3, 1},
		[8]=  {4, 3, 1},
		[9]= {2, 3, 1},
	},
	[3]= {
		[1]=  {4, 2, 3, 5, 6},
		[2]=  {4, 2, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {2, 4, 3, 1},
		[5]=  {1, 2, 3, 4},
		[6]=  {2, 4, 3, 1},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]= {2, 1, 3, 4},
	},
	[4]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]= {2, 1, 4, 3, 5, 6},
	},
	[5]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {2, 1, 4, 3, 5, 6},
	},
	[6]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {2, 1, 4, 3, 5, 6},
	},
} or PallyPower.IsTBC and {
	[1] = {
		[1]=  {4},
		[2]=  {4},
		[3]=  {3, 1},
		[4]=  {3, 1},
		[5]=  {3, 2},
		[6]=  {4},
		[7]=  {4},
		[8]=  {4},
		[9]=  {4},
		[10]= {3, 2},
	},
	[2] = {
		[1]=  {4, 3, 2},
		[2]=  {4, 3, 2},
		[3]=  {1, 3, 4},
		[4]=  {1, 3, 4},
		[5]=  {1, 3, 2},
		[6]=  {4, 3, 2},
		[7]=  {4, 3, 1},
		[8]=  {4, 3, 1},
		[9]=  {1, 3, 4},
		[10]= {2, 3, 1},
	},
	[3]= {
		[1]=  {4, 2, 3, 5, 6},
		[2]=  {4, 2, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {2, 4, 3, 1},
		[5]=  {1, 2, 3, 4},
		[6]=  {2, 4, 3, 1},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {2, 4, 3, 1},
		[10]= {2, 1, 3, 4},
	},
	[4]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {1, 2, 4, 3, 5, 6},
		[10]= {2, 1, 4, 3, 5, 6},
	},
	[5]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {1, 2, 4, 3, 5, 6},
		[10]=  {2, 1, 4, 3, 5, 6},
	},
	[6]= {
		[1]=  {2, 4, 3, 5, 6},
		[2]=  {2, 4, 3, 5, 6},
		[3]=  {1, 4, 3, 5, 6},
		[4]=  {1, 2, 4, 3, 5, 6},
		[5]=  {1, 2, 4, 3, 5, 6},
		[6]=  {2, 1, 4, 3, 5, 6},
		[7]=  {1, 4, 3, 5, 6},
		[8]=  {1, 4, 3, 5, 6},
		[9]=  {1, 2, 4, 3, 5, 6},
		[10]=  {2, 1, 4, 3, 5, 6},
	},
} or {
	[1] = {
		[1]=  {3},
		[2]=  {3},
		[3]=  {3},
		[4]=  {3},
		[5]=  {3},
		[6]=  {3},
		[7]=  {3},
		[8]=  {3},
		[9]=  {3},
		[10]= {3},
		[11]= {3},
	},
	[2] = {
		[1]=  {2, 3},
		[2]=  {2, 3},
		[3]=  {1, 3},
		[4]=  {1, 3},
		[5]=  {1, 3},
		[6]=  {2, 3},
		[7]=  {1, 3},
		[8]=  {1, 3},
		[9]=  {1, 3},
		[10]= {2, 3},
		[11]= {2, 3},
	},
	[3]= {
		[1]=  {2, 4, 3},
		[2]=  {2, 4, 3},
		[3]=  {1, 4, 3},
		[4]=  {1, 2, 3},
		[5]=  {1, 2, 3},
		[6]=  {2, 1, 3},
		[7]=  {1, 4, 3},
		[8]=  {1, 4, 3},
		[9]=  {1, 2, 3},
		[10]= {2, 4, 3},
		[11]= {2, 1, 3},
	},
	[4]= {
		[1]=  {2, 4, 3},
		[2]=  {2, 4, 3},
		[3]=  {1, 4, 3},
		[4]=  {1, 2, 4, 3},
		[5]=  {1, 2, 4, 3},
		[6]=  {2, 1, 4, 3},
		[7]=  {1, 4, 3},
		[8]=  {1, 4, 3},
		[9]=  {1, 2, 4, 3},
		[10]= {2, 4, 3},
		[11]= {2, 1, 4, 3},
	},
}
-- Layouts
PallyPower.Layouts = PallyPower.IsVanilla and {
	["Layout 1"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},

	},
	["Layout 2"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},
	},	
	["Layout 3"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[9] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},
	["Layout 4"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},	
	["Layout 5"] = { 	
					c = {
							[1] = {	
									x = -0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = -1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = -2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = -3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = -4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = -5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = -6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = -7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = -9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = 3, y = 0},
    			rf = {x = 2, y = 0},
		 		au = {x = 1, y = 0},
	},
} or PallyPower.IsTBC and {
	["Layout 1"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -8, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[10] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},

	},
	["Layout 2"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -8, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[10] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},
	},	
	["Layout 3"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[9] = {
									x = 8, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[10] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},
	["Layout 4"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = 8, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[10] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},	
	["Layout 5"] = { 	
					c = {
							[1] = {	
									x = -0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = -1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = -2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = -3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = -4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = -5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = -6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = -7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = -8, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[10] = {
									x = -9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = 3, y = 0},
    			rf = {x = 2, y = 0},
		 		au = {x = 1, y = 0},
	},
} or {
	["Layout 1"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -8, 
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[10] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
							[11] = {
									x = 0, y = -10,
									p = { 
											[1] = {x = 1, y = 0},
											[2] = {x = 1, y = -1},
											[3] = {x = 1, y = -2},
											[4] = {x = 1, y = -3},
											[5] = {x = 1, y = -4},
											[6] = {x = 1, y = -5},
											[7] = {x = 1, y = -6},
											[8] = {x = 1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},

	},
	["Layout 2"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[2] = {
									x = 0, y = -1, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[3] = {
									x = 0, y = -2, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[4] = {
									x = 0, y = -3, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[5] = {
									x = 0, y = -4, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[6] = {
									x = 0, y = -5, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[7] = {
									x = 0, y = -6, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[8] = {
									x = 0, y = -7, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[9] = {
									x = 0, y = -8, 
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[10] = {
									x = 0, y = -9,
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
							[11] = {
									x = 0, y = -10,
									p = { 
											[1] = {x = -1, y = 0},
											[2] = {x = -1, y = -1},
											[3] = {x = -1, y = -2},
											[4] = {x = -1, y = -3},
											[5] = {x = -1, y = -4},
											[6] = {x = -1, y = -5},
											[7] = {x = -1, y = -6},
											[8] = {x = -1, y = -7},
										},
								},
		 		},
				ab = {x = 0, y = 1},
    			rf = {x = 0, y = 2},
		 		au = {x = 0, y = 3},
	},	
	["Layout 3"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[9] = {
									x = 8, y = 0, 
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[10] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
							[11] = {
									x = 10, y = 0,
									p = { 
											[1] = {x = 0, y = -1},
											[2] = {x = 0, y = -2},
											[3] = {x = 0, y = -3},
											[4] = {x = 0, y = -4},
											[5] = {x = 0, y = -5},
											[6] = {x = 0, y = -6},
											[7] = {x = 0, y = -7},
											[8] = {x = 0, y = -8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},
	["Layout 4"] = { 	
					c = {
							[1] = {	
									x = 0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = 1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = 2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = 3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = 4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = 5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = 6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = 7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = 8, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[10] = {
									x = 9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[11] = {
									x = 10, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = -1, y = 0},
    			rf = {x = -2, y = 0},
		 		au = {x = -3, y = 0},
	},	
	["Layout 5"] = { 	
					c = {
							[1] = {	
									x = -0, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[2] = {
									x = -1, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[3] = {
									x = -2, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[4] = {
									x = -3, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[5] = {
									x = -4, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[6] = {
									x = -5, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[7] = {
									x = -6, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
									},
							[8] = {
									x = -7, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[9] = {
									x = -8, y = 0, 
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[10] = {
									x = -9, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
							[11] = {
									x = -10, y = 0,
									p = { 
											[1] = {x = 0, y = 1},
											[2] = {x = 0, y = 2},
											[3] = {x = 0, y = 3},
											[4] = {x = 0, y = 4},
											[5] = {x = 0, y = 5},
											[6] = {x = 0, y = 6},
											[7] = {x = 0, y = 7},
											[8] = {x = 0, y = 8},
										},
								},
		 		},
				ab = {x = 3, y = 0},
    			rf = {x = 2, y = 0},
		 		au = {x = 1, y = 0},
	},
 }